<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>标记为机器学习的活跃问题 - Thinbug</title>
    <link>https://stackoverflow.com/questions/tagged/?tagnames=machine-learning&sort=active</link>
    <description>来自 stackoverflow.com 的最新 30 个</description>
    <lastBuildDate>Sat, 16 Dec 2023 03:13:51 GMT</lastBuildDate>
    <item>
      <title>尽管进行了标准化和交叉验证，模型性能仍面临挑战：使用 Automobile.tn 数据进行的案例研究（1766 条条目）"</title>
      <link>https://stackoverflow.com/questions/77669285/challenges-in-model-performance-despite-standardization-and-cross-validation-a</link>
      <description><![CDATA[从 sklearn.model_selection 导入 cross_val_score
从 sklearn.linear_model 导入 LinearRegression
创建线性回归模型的实例
线性模型=线性回归()
应用 5 倍交叉验证
cross_val_scores = cross_val_score（线性模型，scaled_data，y，cv = 5，评分=&#39;neg_mean_squared_error&#39;）
分数通常为负数，因为 scikit-learn 为了方便而反转了符号
将分数转换为正值
mse_scores = -cross_val_scores
显示结果
print(&quot;R_squared:&quot;,r_squared)
print(&quot;RMSE:&quot;,rmse)
输出：R_squared：0.34315292365076344
均方根误差：50511.93582816874]]></description>
      <guid>https://stackoverflow.com/questions/77669285/challenges-in-model-performance-despite-standardization-and-cross-validation-a</guid>
      <pubDate>Fri, 15 Dec 2023 23:34:17 GMT</pubDate>
    </item>
    <item>
      <title>如何将图像文件夹中的每个图像与其相应的强度标签（单独存储在 CSV 文件中）配对？</title>
      <link>https://stackoverflow.com/questions/77668865/how-can-i-pair-each-image-from-a-folder-of-images-along-with-its-corresponding-i</link>
      <description><![CDATA[最终目标是训练机器学习模型来预测每个图像的强度结果和 label_1。
问题描述：
我有一个图像文件夹 (image_folder)，其中包含 img_1.jpg、img_2.jpg、... 和一个包含 3 列的单独 csv 文件：label_1、强度、image_name &gt;：

问题：
如何确保从“images_folder”读取的每个图像与其相应的“label_1”以及从“csv_file”获取的“强度”配对？应采用哪些步骤或方法来保证处理过程中来自 CSV_file 的图像与其各自标签的准确匹配？
我有这个代码，但我不知道
我怎样才能更好地表示这一点并有效地组织这些数据以更好地训练机器学习模型。
导入 pandas 作为 pd
导入CV2
导入操作系统
train_data_path = r&#39;数据\train.csv&#39;
df = pd.read_csv(train_data_path)

# 从 CSV 文件中提取 file_names
file_names = df[&#39;文件名&#39;].tolist()

# 获取图像文件列表
图像= r“\图像”;
图像文件= []
对于 os.walk(images) 中的 root、_、文件：
    image_files.extend([os.path.join(root, f) for f in files])


组合特征 = []

# 迭代 img_names
对于 file_names 中的 file_name：
    image_file = os.path.join(图像, file_name)
    图像 = cv2.imread(image_file)

    强度 = df[df[&#39;文件名&#39;] == 文件名][
        &#39;强度&#39;].item()
    可见性 = df[df[&#39;文件名&#39;] == 文件名][
        &#39;Label_1&#39;].item()
]]></description>
      <guid>https://stackoverflow.com/questions/77668865/how-can-i-pair-each-image-from-a-folder-of-images-along-with-its-corresponding-i</guid>
      <pubDate>Fri, 15 Dec 2023 21:15:04 GMT</pubDate>
    </item>
    <item>
      <title>Python 中的帧插值</title>
      <link>https://stackoverflow.com/questions/77668744/frame-interpolation-in-python</link>
      <description><![CDATA[]]></description>
      <guid>https://stackoverflow.com/questions/77668744/frame-interpolation-in-python</guid>
      <pubDate>Fri, 15 Dec 2023 20:45:42 GMT</pubDate>
    </item>
    <item>
      <title>选择单词后无法将实体分配给对话框流中的单词</title>
      <link>https://stackoverflow.com/questions/77668297/not-able-to-assign-entity-to-word-in-dialogflow-after-selecting-the-word</link>
      <description><![CDATA[我们可以通过**选择**单词**来在对话流中的短语中分配实体。但看不到弹出窗口。

我正在尝试分配系统实体@sys.number，但无法。
尝试将实体分配给单词，但即使选择后也没有弹出窗口可见。]]></description>
      <guid>https://stackoverflow.com/questions/77668297/not-able-to-assign-entity-to-word-in-dialogflow-after-selecting-the-word</guid>
      <pubDate>Fri, 15 Dec 2023 18:51:47 GMT</pubDate>
    </item>
    <item>
      <title>随机森林机器学习（R 平方问题）[关闭]</title>
      <link>https://stackoverflow.com/questions/77667644/machine-learning-with-random-forest-r-squared-problem</link>
      <description><![CDATA[]]></description>
      <guid>https://stackoverflow.com/questions/77667644/machine-learning-with-random-forest-r-squared-problem</guid>
      <pubDate>Fri, 15 Dec 2023 16:41:24 GMT</pubDate>
    </item>
    <item>
      <title>根据时态和非时态数据进行预测[关闭]</title>
      <link>https://stackoverflow.com/questions/77667561/making-predictions-from-temporal-and-non-temporal-data</link>
      <description><![CDATA[我正在研究一个回归问题来预测由 2 个参数组成的目标。
这两个参数将根据时间 (YYYY-MM-DD HH:MM) 和非时间数据组成的特征进行预测。
我开始基于“决策树回归”构建 Python 代码算法。
尽管数据趋势看起来令人满意，但我的模型似乎产生了与用于训练/测试的数据范围相同的输出。
我想知道我的方法好不好。
我偶然发现了一些处理相同问题的论文，并使用 CNN-LSTM 模型等进行了解决。
这是我的代码的链接（Google Colab 文件）：
https://drive.google.com/file/d/1ar5Z8kMXx_9slc1e_MMzaAcQAvx5lmzr/查看？usp=共享
期待您的帮助。]]></description>
      <guid>https://stackoverflow.com/questions/77667561/making-predictions-from-temporal-and-non-temporal-data</guid>
      <pubDate>Fri, 15 Dec 2023 16:25:51 GMT</pubDate>
    </item>
    <item>
      <title>定制训练的 yolov7 模型准确率为 95%，但几乎可以检测到所有内容，但不能检测到我想在网络摄像头上检测到的对象 [关闭]</title>
      <link>https://stackoverflow.com/questions/77667354/custom-trained-yolov7-model-is-95-percent-accurate-but-detects-almost-everything</link>
      <description><![CDATA[使用 cuda 在 VS Code 中使用 yolov7 训练模型。我使用了一个预先标记的数据集，我认识的人已经成功地完成了与我相同的任务。我使用 500 张图像对模型进行了 1000 个时期的训练。在图表中，模型是准确的，但是当我用网络摄像头测试它时，它检测到所有东西就像汽水罐一样（我正在尝试检测汽水罐）。但是当我向它展示一个汽水罐时，它不会检测到它，但它会像汽水罐一样检测到我的脸、墙壁、冰箱。
问题是，我将包含模型的文件夹发送给了我的程序员朋友。在他的计算机上，该模型运行良好并且正在检测汽水罐。是否有原因导致该模型在他的电脑上运行良好但在我的电脑上运行不佳？]]></description>
      <guid>https://stackoverflow.com/questions/77667354/custom-trained-yolov7-model-is-95-percent-accurate-but-detects-almost-everything</guid>
      <pubDate>Fri, 15 Dec 2023 15:45:07 GMT</pubDate>
    </item>
    <item>
      <title>如何从 ML 模型制作房屋蓝图 [关闭]</title>
      <link>https://stackoverflow.com/questions/77667125/how-to-make-house-blueprints-from-ml-model</link>
      <description><![CDATA[我是机器学习新手，想要创建一个模型，可以为我们提供基于用户需求的平面图。我们的目标是制作一个能够满足用户需求的 Flutter 应用程序，并根据 ML 模型制作一个平面图。我对 flutter 有一定的了解，但对 ML 或 python 零知识。
我期待指导如何制作图像数据集并处理它，然后从数据集中如何制作 ML 模型，然后从该模型如何根据用户要求生成平面图。]]></description>
      <guid>https://stackoverflow.com/questions/77667125/how-to-make-house-blueprints-from-ml-model</guid>
      <pubDate>Fri, 15 Dec 2023 15:01:42 GMT</pubDate>
    </item>
    <item>
      <title>批量丢失也可以用作张量流转换模型的输入吗？</title>
      <link>https://stackoverflow.com/questions/77666461/can-a-batched-lost-also-be-used-as-input-for-a-tensorflow-conv-model</link>
      <description><![CDATA[]]></description>
      <guid>https://stackoverflow.com/questions/77666461/can-a-batched-lost-also-be-used-as-input-for-a-tensorflow-conv-model</guid>
      <pubDate>Fri, 15 Dec 2023 13:07:48 GMT</pubDate>
    </item>
    <item>
      <title>我可以扩展和改进神经网络模型而无需从头开始重新训练吗？ [关闭]</title>
      <link>https://stackoverflow.com/questions/77666392/can-i-expand-and-improve-a-neural-network-model-without-retraining-from-scratch</link>
      <description><![CDATA[假设我已经训练了一个神经网络，用于使用 MNIST 数据集对数字进行分类。如果我还想能够识别字符“A”，我可以以某种方式利用已经训练好的神经网络吗？新模型最终应该能够区分：“0-1-2-3-4-5-6-7-8-9-A”
我猜我需要更改神经网络，以便它在输出层中容纳额外的可能输出。
我在想也许我可以使用初始模型中获得的权重作为新模型中相应权重的起始值。这到底有什么用，还是我从头开始一个新模型会更好？
我知道 Mnist 并不是一个真正大的数据集，重新开始也没什么大不了的，但我认为这个问题仍然很有趣，并且在处理更大的数据集或更复杂的系统时会变得更加相关。]]></description>
      <guid>https://stackoverflow.com/questions/77666392/can-i-expand-and-improve-a-neural-network-model-without-retraining-from-scratch</guid>
      <pubDate>Fri, 15 Dec 2023 12:55:35 GMT</pubDate>
    </item>
    <item>
      <title>OutOfMemoryError：LLM 中的 CUDA 内存不足</title>
      <link>https://stackoverflow.com/questions/77665954/outofmemoryerror-cuda-out-of-memory-in-llm</link>
      <description><![CDATA[我有一个文本列表，我需要将每个文本发送到大型语言模型（llama2-7b）。但是我遇到了 CUDA 内存不足错误。我在 Google Colab 上的 A100 上运行。这是我的尝试：
path = “meta-llama/Llama-2-7b-chat-hf”
tokenizer = LlamaTokenizer.from_pretrained(路径)
模型 = LlamaForCausalLM.from_pretrained(path).to(“cuda”)


def actuate_with_model(查询, input_text=&quot;&quot;):
    if pd.isna(input_text): return (“NaN”)
    别的：
        提示=查询+输入文本
        输入 = tokenizer(提示, return_tensors=“pt”, return_attention_mask=False).to(“cuda”)
        generate_ids = model.generate(**输入)
        输出 = tokenizer.batch_decode(outputs)[0]
        返回输出


def process_data(查询,批处理):
  回复 = []
  对于范围内的 i(len(batch))：
      响应 = interact_with_model(查询, 批次[i])
      响应.追加（响应）
  返回响应



query_1 = “总结以下文本”
响应_1 = []
对于范围内的 i(0,len(输入),50)：
    sub_inputs = 输入[i:i+50]
    response_1.append(process_data(query_1,batch=sub_inputs))

我尝试每次向模型发送 50 个样本的文本，但这也不起作用。问题出在哪里？]]></description>
      <guid>https://stackoverflow.com/questions/77665954/outofmemoryerror-cuda-out-of-memory-in-llm</guid>
      <pubDate>Fri, 15 Dec 2023 11:25:41 GMT</pubDate>
    </item>
    <item>
      <title>Python ValueError：给定的列不是数据帧的列</title>
      <link>https://stackoverflow.com/questions/77663537/python-valueerror-a-given-column-is-not-a-column-of-the-dataframe</link>
      <description><![CDATA[]]></description>
      <guid>https://stackoverflow.com/questions/77663537/python-valueerror-a-given-column-is-not-a-column-of-the-dataframe</guid>
      <pubDate>Thu, 14 Dec 2023 23:15:42 GMT</pubDate>
    </item>
    <item>
      <title>随机森林分类器演示期间用户输入的问题</title>
      <link>https://stackoverflow.com/questions/77653884/a-problem-with-the-user-input-during-the-random-forest-classifier-demonstration</link>
      <description><![CDATA[我使用随机森林分类器获得了超过 90% 的准确率，但我担心其余算法给出的结果要低得多：
包含结果的表格
但这不是主要问题。问题是，当我使用用户输入时，预测是 100% 错误的。用户输入的列的顺序对应于训练数据集列的位置。
模型 = RandomForestClassifier()
model.fit(X_train, y_train)
预测 = model.predict(X_test)
acc = precision_score(y_test, 预测) # 输出：0.91

X_test_user = df_user_compounds_1.to_numpy()
user_input_predictions_1 = model.predict(X_test_user) #
user_input_predictions_1 # 输出： array([0, 0, 0, 0, 0], dtype=int64)，但应该是： array([1, 1, 1, 1, 1],dtype=int64)

有人知道为什么会发生这种情况吗？
数据集经过预处理 - 没有缺失值，没有重复，使用 RandomOverSampler 进行平衡，使用 MinMaxScaler 进行缩放，没有负值，并且包含 11 个特征/7K 行。
……
非常感谢@ElvinJafarov。这些是来自 df_user_compounds_1 的部分，以及根据您的建议生成的 X_test。

由于我已经使用了 MinMaxScaler()，因此我必须向 df_user_compounds_1 添加另外两行，其中包含相应的最小值和最大值，以模拟与原始缩放相同的缩放。我通过 df.describe(include=“all”) 找到了最大值和最小值，将这两行连接到用户输入数据帧并缩放 
我对结果很满意：前 5 个必须是 1，即 5 个中的 4 个 &lt; img alt=&quot;结果&quot; src=&quot;https://i.stack.imgur.com/WssFz.png&quot; /&gt;]]></description>
      <guid>https://stackoverflow.com/questions/77653884/a-problem-with-the-user-input-during-the-random-forest-classifier-demonstration</guid>
      <pubDate>Wed, 13 Dec 2023 13:17:28 GMT</pubDate>
    </item>
    <item>
      <title>模块“wandb”没有属性“apis”</title>
      <link>https://stackoverflow.com/questions/77298910/module-wandb-has-no-attribute-apis</link>
      <description><![CDATA[我正在尝试在通过 SSH 在服务器上运行的项目中使用 wandb。我创建并配置了虚拟环境，但使用 wandb 时，遇到错误“模块‘wandb’没有属性‘apis’”。服务器运行 Python 3.6.8 并安装了 wandb-0.15.12。但是，当我使用“wandb login”或任何其他 wandb 命令时，它会抛出错误。谁能帮我解决这个问题吗？
回溯（最近一次调用最后一次）：
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/bin/wandb”，第5行，在&lt;模块&gt;中。
    从 wandb.cli.cli 导入 cli
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/lib64/python3.6/site-packages/wandb/__init__.py”，第 27 行，在  中
    从 wandb 导入 sdk 作为 wandb_sdk
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/lib64/python3.6/site-packages/wandb/sdk/__init__.py”，第 4 行，在  中
    来自 .artifacts.artifact 导入 Artifact # noqa: F401
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/lib64/python3.6/site-packages/wandb/sdk/artifacts/artifact.py”，第 36 行，在  中
    从 wandb.apis.normalize 导入 normalize_exceptions
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/lib64/python3.6/site-packages/wandb/apis/__init__.py”，第 44 行，在  中
    from .public import Api as PublicApi # noqa
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/lib64/python3.6/site-packages/wandb/apis/public.py”，第 51 行，在  中
    从 wandb.sdk.launch.errors 导入 LaunchError
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/lib64/python3.6/site-packages/wandb/sdk/launch/__init__.py”，第 1 行，在  中
    从 ._launch 导入启动
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/lib64/python3.6/site-packages/wandb/sdk/launch/_launch.py​​”，第 12 行，在  中
    从 .agent 导入 LaunchAgent
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/lib64/python3.6/site-packages/wandb/sdk/launch/agent/__init__.py”，第 1 行，在  中
    从 .agent 导入 LaunchAgent
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/lib64/python3.6/site-packages/wandb/sdk/launch/agent/agent.py”，第 15 行，在  中
    从 wandb.sdk.launch._launch_add 导入 launch_add
  文件“/home/tcouto/mestrado_andrey/psla/venv-psla/lib64/python3.6/site-packages/wandb/sdk/launch/_launch_add.py”，第 5 行，在  中
    将 wandb.apis.public 导入为 public
AttributeError：模块“wandb”没有属性“apis”


我尝试在另一个虚拟环境中重新安装并设置它，但同样的错误不断发生，并且文件夹内没有任何其他具有该名称的文件]]></description>
      <guid>https://stackoverflow.com/questions/77298910/module-wandb-has-no-attribute-apis</guid>
      <pubDate>Mon, 16 Oct 2023 00:41:27 GMT</pubDate>
    </item>
    <item>
      <title>DataLoader 工作线程意外退出？</title>
      <link>https://stackoverflow.com/questions/76086644/dataloader-worker-exited-unexpectedly</link>
      <description><![CDATA[我正在运行这篇 Medium 文章中看到的代码：https://medium.com/@bentanweihao/training-a-custom-object- detector-in-half-a-day-with-yolov8-5e1475fe201e&lt; /p&gt;
具体是实际训练部分：
来自 ultralytics 导入
YOLO模型 = YOLO(“yolov8n.pt”)
model.train(data=&quot;data.yaml&quot;, epochs=20)
指标 = model.val()

我收到了这个错误：
 25 defdecorate_context(*args, **kwargs):
     26 与 self.__class__():
...
--&gt;第999章
   1000 if isinstance(e, 队列.空):
   1001 返回（假，无）

RuntimeError：DataLoader 工作线程（pid(s) 21812、23384、6272、20544、27792、27784、17928、15588、28072、24112）意外退出

有人有建议吗？]]></description>
      <guid>https://stackoverflow.com/questions/76086644/dataloader-worker-exited-unexpectedly</guid>
      <pubDate>Sun, 23 Apr 2023 18:45:29 GMT</pubDate>
    </item>
    </channel>
</rss>